django_movie/urls.py
from django_movie import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 

movies/urls.py
from django.urls import path
from  movies import views

urlpatterns = [
    path('', views.MovieView.as_view(), name='main'),
    path('<slug:slug>', views.MovieDetailView.as_view(), name='movie_detail')
]

movies/models.py
from django.db import models
from datetime import date
from django.urls import reverse
# Create your models here.


class Category(models.Model):
    """Категории"""
    name = models.CharField('Категория', max_length=150)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=150, unique=True)

    def __str__(self) -> str:
        return self.name
    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Actors(models.Model):
    """Актеры и режиссеры"""
    name = models.CharField('Имя актера', max_length=150)
    age = models.PositiveSmallIntegerField('Возраст', default=0)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to='actors/')

    def __str__(self) -> str:
        return self.name
    class Meta:
        verbose_name = "Актеры и режиссеры"
        verbose_name_plural = "Актеры и режиссеры"

class Genre(models.Model):
    """Жанры"""
    name = models.CharField('Категория', max_length=150)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=150, unique=True)

    def __str__(self) -> str:
        return self.name
    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"

    
class Movie(models.Model):
    """Фильмы"""
    title = models.CharField('Название', max_length=100)
    tagline = models.CharField('Слоган', max_length=100)
    description = models.TextField('Описание')
    poster = models.ImageField("Постер", upload_to='posters/')
    year = models.PositiveSmallIntegerField("Год выхода", default=2023)
    country = models.CharField("Страна", max_length=100)
    directions = models.ManyToManyField(Actors, verbose_name='Режиссеры', related_name='film_director')
    actors = models.ManyToManyField(Actors, verbose_name='Актеры', related_name='film_actor')
    genres = models.ManyToManyField(Genre, verbose_name='Жанры')
    world_premiere = models.DateField("Премьера в мире", default=date.today)
    budget =  models.PositiveIntegerField("Бюджет фильма", default=0, help_text="Указывать в долларах")
    feels_in_usa = models.PositiveIntegerField("Сборы в США", default=0, help_text="Указывать в долларах")
    feels_in_world = models.PositiveIntegerField("Сборы в мире", default=0, help_text="Указывать в долларах")
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=150, unique=True)
    draft = models.BooleanField("Черновик", default=False)
    def __str__(self) -> str:
        return self.title
    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"
    def get_absolute_url(self):
        return reverse('movie_detail', kwargs={'slug':self.url})


class MovieShots(models.Model):
    """Кадры из фильма"""
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to='movie_shots/')
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)
    def __str__(self) -> str:
        return self.title
    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"

class RatingStar(models.Model):
    """Звезды рейтинга"""
    value = models.SmallIntegerField("Значение", default=0)
    def __str__(self) -> str:
        return self.value
    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"

class Rating(models.Model):
    """Рейтинги"""
    ip = models.CharField("IP адресс", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="Звезда")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="Фильм")
    def __str__(self) -> str:
        return f'{self.star}-{self.value}' 
    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Reviews(models.Model):
    """"""
    email = models.EmailField()
    name = models.CharField('Имя', max_length=150)
    text = models.TextField('Сообщение')
    parents = models.ForeignKey('self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True)
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)
    def __str__(self) -> str:
        return f'{self.star}-{self.value}' 
    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

movies/views.py
from django.shortcuts import render
from django.views.generic import  ListView, DetailView

from .models import Movie


class MovieView(ListView):
    """Спiсок фильмов"""
    model = Movie
    queryset = Movie.objects.filter(draft=False)
    template_name = 'movies/movies.html' #это нужно для того чтобы джанго находил путь на авто. он к имени модели добавляет _list

class MovieDetailView(DetailView):
    """Полное описание и детали к фильму"""
    model = Movie
    slug_field = 'url' 
    #тут уже _detail и поэтому не нужен template_name
    

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <!-- //Meta tag Keywords -->
    <title>{% block title %} {% endblock title %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- //Meta tag Keywords -->
    <!-- Custom-Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Bootstrap-Core-CSS -->
    <!--/ Style-CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
    <!--// Style-CSS -->
    <!-- font-awesome-icons -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <!-- //font-awesome-icons -->
    <!-- /Fonts -->
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700"
          rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900"
          rel="stylesheet">
    <!-- //Fonts -->
</head>
<body>
<div id="page" class="page">
    <div class="main-banner bg {% block header %}  {% endblock header %}" id="home">
        {% include 'include/header.html' %}
    </div>
    <ol class="breadcrumb editContent">
        <li class="breadcrumb-item">
            <a href="{% url 'main' %}" class="editContent">Home</a>
        </li>
        <li class="breadcrumb-item active editContent">Single Page</li>
    </ol>
    {% block content %}

    {% endblock content %}
    {% include 'include/footer.html' %}
</div>
</body>
</html>

templates/include/footer.html
<footer class="editContent">
  <div class="container">
      <div class="row footer-top">
          <div class="col-lg-4 footer-grid_section_w3layouts">
              <h2 class="logo-2 mb-lg-4 mb-3">
                  <a href="{% url 'main' %}" class="editContent">
                              <span class="fa" aria-hidden="true">
                                  Django School
                              </span>
                  </a>
              </h2>
              <p class="editContent">
                  Канал для программистов и людей, которые хотят развиваться в сфере IT.
                  Видео уроки по python 3, Django 2, Django 3, JavaScript, Vue.js, HTML, CSS
                  и многое другое.
              </p>
              <h4 class="sub-con-fo ad-info my-4 editContent">Catch on Social</h4>
              <ul class="w3layouts_social_list media-soc list-unstyled">
                  <li>
                      <a href="#" class="w3pvt_facebook editContent">
                          <span class="fa fa-facebook-f"></span>
                      </a>
                  </li>
                  <li>
                      <a href="#" class="w3pvt_twitter editContent">
                          <span class="fa fa-twitter"></span>
                      </a>
                  </li>
                  <li>
                      <a href="#" class="w3pvt_dribble editContent">
                          <span class="fa fa-dribbble"></span>
                      </a>
                  </li>
                  <li>
                      <a href="#" class="w3pvt_google editContent">
                          <span class="fa fa-google-plus"></span>
                      </a>
                  </li>
              </ul>
          </div>
          <div class="col-lg-8 footer-right">
              <div class="w3layouts-news-letter">
                  <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3">
                      Newsletter</h3>

                  <p class="editContent">By subscribing to our mailing list you will always
                      get latest news and updates from us.</p>
                  <form action="#" method="post" class="w3layouts-newsletter">
                      <input type="email" name="Email" class="editContent"
                             placeholder="Enter your email..." required="">
                      <button class="btn1 btn"><span class="fa fa-paper-plane-o"
                                                     aria-hidden="true"></span></button>

                  </form>
              </div>
              <div class="row mt-lg-4 bottom-w3layouts-sec-nav mx-0">
                  <div class="col-md-4 footer-grid_section_w3layouts">
                      <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3">
                          Разделы</h3>
                      <ul class="list-unstyled w3layouts-icons">
                          <li>
                              <a href="{% url 'main' %}" class="editContent">Главная</a>
                          </li>
                          <li>
                              <a href="about.html" class="editContent">Категории</a>
                          </li>
                          <li>
                              <a href="contact.html" class="editContent">Контакты</a>
                          </li>
                      </ul>
                  </div>
                  <div class="col-md-4 footer-grid_section_w3layouts">
                      <!-- social icons -->
                      <div class="agileinfo_social_icons">
                          <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3">
                              Pages</h3>
                          <ul class="list-unstyled w3layouts-icons">

                              <li>
                                  <a href="#" class="editContent">About Us</a>
                              </li>
                              <li>
                                  <a href="#" class="editContent">About Us</a>
                              </li>
                              <li>
                                  <a href="#" class="editContent">About Us</a>
                              </li>
                              <li>
                                  <a href="#" class="editContent">About Us</a>
                              </li>
                              <li>
                                  <a href="#" class="editContent">About Us</a>
                              </li>
                          </ul>
                      </div>
                      <!-- social icons -->
                  </div>
                  <div class="col-md-4 footer-grid_section_w3layouts my-md-0 my-5">
                      <h3 class="footer-title text-uppercase text-wh mb-lg-4 mb-3 editContent">
                          Contact Info</h3>
                      <div class="contact-info">
                          <div class="footer-address-inf my-4">
                              <h4 class="ad-info mb-2 editContent">Email </h4>
                              <p class="editContent"><a href="mailto:info@example.com">info@example.com</a>
                              </p>
                          </div>
                          <div class="footer-address-inf">
                              <h4 class="ad-info mb-2 editContent">Location</h4>
                              <p class="editContent">New York City</p>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</footer>
<!-- //footer -->
<div class="cpy-right py-3">
  <div class="container">
      <div class="row">
          <p class="col-md-10 text-left">© 2019 DjangoMovie. All rights reserved | Design by
              <a href="https://djangochannel.com"> DJANGO SCHOOL.</a>
          </p>
          <!-- move top icon -->
          <a href="#home" class="move-top text-right col-md-2"><span
                  class="fa fa-long-arrow-up" aria-hidden="true"></span></a>
          <!-- //move top icon -->
      </div>
  </div>
</div>

templates/include/header.html
<header class="header">
    <div class="container-fluid px-lg-5">
        <!-- nav -->
        <nav class="py-4">
            <div id="logo">
                <h1><a href="{% url 'main' %}" class="editContent"
                       style="outline: none; outline-offset: -2px; cursor: inherit; color: rgb(255, 255, 255); font-size: 40px; background-color: rgba(0, 0, 0, 0); font-family: Source Sans Pro;, sans-serif;">DjangoMovie</a>
                </h1>
            </div>

            <label for="drop" class="toggle">Menu</label>
            <input type="checkbox" id="drop">
            <ul class="menu mt-2">
                <li class="active"><a href="{% url 'main' %}">Главная</a></li>
                <li>
                    <!-- First Tier Drop Down -->
                    <label for="drop-2" class="toggle">Категории <span
                            class="fa fa-angle-down" aria-hidden="true"></span> </label>
                    <a href="#">Категории <span class="fa fa-angle-down"
                                                aria-hidden="true"></span></a>
                    <input type="checkbox" id="drop-2">
                    <ul>
                        <li><a href="moviesingle.html">Фильмы</a></li>
                        <li><a href="moviesingle.html">Сериалы</a></li>
                        <li><a href="moviesingle.html">Мультфильмы</a></li>
                    </ul>
                </li>
                <li><a href="contact.html"
                       style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">Вход</a>
                </li>
            </ul>
        </nav>
        <!-- //nav -->
    </div>
</header>
<!-- //header -->
<!--/banner-->
<div class="banner-info">
    <p class="editContent">лучший сайт на django 3</p>
    <h3 class="mb-4 editContent">Все о кино</h3>
    <div class="ban-buttons">


    </div>
</div>
<!--// banner-inner -->

templates/include/sidebar.html
<div class="search-bar w3layouts-newsletter">
    <h3 class="sear-head editContent">Поиск фильма</h3>
    <form action="#" method="post" class="d-flex editContent">
        <input type="search" placeholder="Введите название..." name="search"
               class="form-control" required="">
        <button class="btn1 btn"><span class="fa fa-search"
                                       aria-hidden="true"></span></button>
    </form>
</div>
<!--preference -->
<div class="left-side my-4">
    <h3 class="sear-head editContent">Жанры</h3>
    <ul class="w3layouts-box-list">
        <li class="editContent">
            <input type="checkbox" class="checked">
            <span class="span editContent">Аниме</span>
        </li>
        <li class="editContent">
            <input type="checkbox" class="checked">
            <span class="span editContent">Боевики</span>
        </li>
        <li class="editContent">
            <input type="checkbox" class="checked">
            <span class="span editContent">Комедии</span>
        </li>
        <li class="editContent">
            <input type="checkbox" class="checked">
            <span class="span editContent">Ужасы</span>
        </li>
    </ul>
</div>
<!-- // preference -->
<!-- discounts -->
<div class="left-side">
    <h3 class="sear-head editContent">Год</h3>
    <ul class="w3layouts-box-list">
        <li class="editContent">
            <input type="checkbox" class="checked">
            <span class="span editContent">2020</span>
        </li>
        <li class="editContent">
            <input type="checkbox" class="checked">
            <span class="span editContent">2019</span>
        </li>
        <li class="editContent">
            <input type="checkbox" class="checked">
            <span class="span editContent">2018</span>
        </li>
        <li>
            <input type="checkbox" class="checked">
            <span class="span editContent">2017</span>
        </li>
        <li class="editContent">
            <input type="checkbox" class="checked">
            <span class="span editContent">2016</span>
        </li>
        <li class="editContent">
            <input type="checkbox" class="checked">
            <span class="span editContent">2015</span>
        </li>
    </ul>
</div>
<!-- //discounts -->
<!-- reviews -->
<div class="customer-rev left-side my-4">
    <h3 class="sear-head editContent">Рейтинг</h3>
    <ul class="w3layouts-box-list">
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="editContent">5.0</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star-o" aria-hidden="true"></span>
                <span class="editContent">4.0</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star-half-o" aria-hidden="true"></span>
                <span class="fa fa-star-o" aria-hidden="true"></span>
                <span class="editContent">3.5</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star-o" aria-hidden="true"></span>
                <span class="fa fa-star-o" aria-hidden="true"></span>
                <span class="editContent">3.0</span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star" aria-hidden="true"></span>
                <span class="fa fa-star-half-o" aria-hidden="true"></span>
                <span class="fa fa-star-o" aria-hidden="true"></span>
                <span class="fa fa-star-o" aria-hidden="true"></span>
                <span class="editContent">2.5</span>
            </a>
        </li>
    </ul>
</div>
<!-- //reviews -->
<!-- deals -->
<div class="deal-leftmk left-side">
    <h3 class="sear-head editContent">Последние добавленные</h3>
    <div class="special-sec1 row mt-3 editContent">
        <div class="img-deals col-md-4">
            <img src="bundles/images/s4.jpg" class="img-fluid" alt="">
        </div>
        <div class="img-deal1 col-md-4">
            <h3 class="editContent">Рэмбо: Последняя кровь</h3>
            <a href="moviesingle.html" class="editContent"></a>
        </div>

    </div>
    <div class="special-sec1 row mt-3 editContent">
        <div class="img-deals col-md-4">
            <img src="bundles/images/s2.jpg" class="img-fluid" alt="">
        </div>
        <div class="img-deal1 col-md-8">
            <h3 class="editContent">Холодное сердце 2</h3>
            <a href="moviesingle.html" class="editContent"></a>
        </div>

    </div>
    <div class="special-sec1 row mt-3 editContent">
        <div class="img-deals col-md-4">
            <img src="bundles/images/s1.jpg" class="img-fluid" alt="">
        </div>
        <div class="img-deal1 col-md-8">
            <h3 class="editContent">К звездам</h3>
            <a href="moviesingle.html" class="editContent"></a>
        </div>

    </div>
    <div class="special-sec1 row mt-3 editContent">
        <div class="img-deals col-md-4">
            <img src="bundles/images/s5.jpg" class="img-fluid" alt="">
        </div>
        <div class="img-deal1 col-md-8">
            <h3 class="editContent">Терминатор: Темные судьбы</h3>
            <a href="moviesingle.html" class="editContent"></a>
        </div>

    </div>
    <div class="special-sec1 row mt-3 editContent">
        <div class="img-deals col-md-4">
            <img src="bundles/images/s3.jpg" class="img-fluid" alt="">
        </div>
        <div class="img-deal1 col-md-8">
            <h3 class="editContent">Джокер</h3>
            <a href="moviesingle.html" class="editContent"></a>
        </div>

    </div>
</div>

templates/movies/base.html
{% extends 'base.html' %}
{% block title %} {% endblock title %}
{% block content %}
    <section class="ab-info-main py-md-5 py-4 editContent"
             style="padding-left: 3rem; padding-right: 3rem;">
        {% block container %}
            <div class="container-fluid py-md-3">
        {% endblock container %}
        <div class="row">
            {% block sidebar %}
                <div class="side-bar col-lg-3">
            {% endblock sidebar %}
            {% include 'include/sidebar.html' %}
            </div>
            {% block movie %}
            {% endblock movie %}
        </div>
        </div>
    </section>
{% endblock content %}

templates/movies/movies.html
{% extends 'movies/base.html' %}
{% block title %} {% endblock title %}
{% block header %} bg1 {% endblock header %}
{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for movie in movie_list %}
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}"
                                   class="editContent">
                                    {{ movie.title }}
                                </a>
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent">{{ movie.tagline }}</span>
                                </div>
                            </div>
                            <ul class="stars">
                                <li><a href="#"><span class="fa fa-star"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star-half-o"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star-half-o"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star-o"
                                                      aria-hidden="true"></span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <!--<div class="grid-img-right mt-4 text-right bg bg1" >
            <span class="money editContent" >Flat 50% Off</span>
            <a href="moviesingle.html" class="btn" >Now</a>
        </div>-->
    </div>
{% endblock movie %}